sudo: required
services:
- docker
cache:
- pip
language: python
python:
- '2.7'
- '3.5'
env:
- TEST_SUITE=functional OPENSHIFT_VERSION=latest
- TEST_SUITE=functional OPENSHIFT_VERSION=3.7
- TEST_SUITE=functional OPENSHIFT_VERSION=3.6
- TEST_SUITE=functional OPENSHIFT_VERSION=1.5
- TEST_SUITE=functional OPENSHIFT_VERSION=1.4
- TEST_SUITE=functional OPENSHIFT_VERSION=1.3
script: tox
install:
- pip install tox-travis coveralls
after_success:
- coveralls
jobs:
  include:
  - stage: lint
    python: '2.7'
    install:
    - pip install tox-travis
    script: tox -e py27-lint
    env:
    - TEST_SUITE=lint OPENSHIFT_VERSION=latest
  - python: '3.5'
    install:
    - pip install tox-travis
    script: tox -e py35-lint
    env:
    - TEST_SUITE=lint OPENSHIFT_VERSION=latest
  - stage: deploy
    script: skip
    deploy:
      provider: pypi
      user: openshift
      password:
        secure: OtT8BL3rmSlag7H+jLNuPl52UOD8HVuohK0d4OQNMTiejZ1ali/fT4K1yCqteLLTalode1KnG/YpqQuOeEEVJCZNqbAeG3VuD4o3sx0hn1ATMwu5RDngovSSVojhKAOMSh/w3TycRysV+x/L5twntGycNUmtDiRGSJFmXGgq0EPLbE6DUv8IMwlhq/ncNz7/RU5KU852kwc6TDHZloHdhOH5ibibi7VCKUlkK/JnAT/OX0uw/j4v6Dvs6CzJ2lrSozUtjP5OxWPh6XRcXNxlxYuTSy7rjqBd05pk3YUAOQt/cEa4581Qu9hSEvhWFSJBjxpggWunTAbeSjqpdY+iqHcoKg+J3ErscIQnsLOwo8nCIKzyn4GMGx/jQYNfWuXGJiOqHFFCyYR16BajQ/gWk78K5MpUDlf2zoyq3NjTp7edY9lWWL7BEgZdd5EY6wI3V7tlGFeNG/iWw2gL3jR+FfUqzEnBnA+EfPUcowLD6rVCsKoxuLs1YyNiOJLzI1lX3FXvntEkVjPH7w5yju2GXWuw/Szgd0MK2HSedV/tp526V/GOkhD1sbQngEVdrIwPI1QbiMX/1pcSvkCvJrKq5EpShZ9iD/D0T92/01x5X3HSx+R3yV3zhB8L3H7RDL/F3HGNbqVPaj9rHAfTJaxWhy6Y3nWpfwQI43cKFCNwF28=
    on:
      tags: true
      repo: openshift/openshift-restclient-python
stages:
- lint
- test
- deploy
